name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out a copy of your repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt

    - name: Build the executable with PyInstaller
      run: pyinstaller --onefile --clean --hidden-import=helius main.py

    - name: Upload the executable as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: solana-alarm-exe
        path: dist/main.exe
